### ISSUE TITLE
Exception when handling custom mentions

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/highfive#213]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/highfive/app.py", line 45, in new_pr
    return handler.run(flask.request.headers['X-GitHub-Event'])
  File "/usr/local/lib/python2.7/dist-packages/highfive/newpr.py", line 71, in run
    self.new_pr()
  File "/usr/local/lib/python2.7/dist-packages/highfive/newpr.py", line 377, in new_pr
    author, to_mention
  File "/usr/local/lib/python2.7/dist-packages/highfive/newpr.py", line 133, in set_assignee
    message += "%s\n\ncc %s" % (mention['message'],
KeyError: 'message'
```

https://github.com/rust-lang/highfive/blob/748c035ca2a913cb3bc95404f8665985736f165c/highfive/newpr.py#L133-L134

@GuillaumeGomez

**Comment by pietroalbini** [comment]
This is probably the cause of https://github.com/rust-lang/rust/pull/60515#issuecomment-489312517

**Comment by GuillaumeGomez** [comment]
Perfect, thanks for the backtrace! I'll send a fix later on today.
